quiz_task:
  description: >
    You are conducting a quiz on {topic}, starting from the basics and progressing to advanced concepts. 
    The quiz will cover fundamental to advance topics related to {topic} and gradually move toward the core subject.

    For example, if the topic is Machine Learning, the quiz will include questions on:

    Python (basics and relevant libraries)
    Data Visualization
    Data Analysis
    Data Preparation
    Machine Learning concepts

    Ask 10 questions and take the user input answers

    if the user choose any options that are not in the choices just make it as incorrect

    Example Question:

    What is a conditional statement in Python?
    A) if else
    B) for
    C) While
    D) None of the above

    example user answers
    A,A,B,C
    ... and so on

    Note:
    1) Ask the question only once; do not repeat it.
    2) The example question is provided solely for your understanding of the question format; do not use that exact question.
    3) Generate all 10 questions and take user input as the choices. After completing this, pass the work to the next agent.
  expected_output: >
    Generate 10 quiz questions on {topic}, starting from foundational concepts and progressing to advanced topics. 
    For all question, take the user's input before passing the task to next agent. 
  agent: Quiz_bot




analyze_task:
  description: >
    Review the user's scores and area of topic to imporve, evaluate their performance, and provide a 
    description of how he performed in the quiz detailed roadmap of the topics they need to learn. Based on their quiz performance, 
    outline the specific topics they should focus on, the time required to master each 
    topic, and a structured timeline for completion. Include prerequisites for each 
    topic to ensure a logical learning progression.

    NOTE:
    1) The topics in the table are in simple to hard
    2) If the user want to learn machine learning so the table contents starts from basic machine learning to advance machine learning topics and so on
    3) Based on the user performace, write the data in the table i mean if he perform well that mean he knows
       the basics so you will give less (	Duration, Days, Time Required) for the topics or else provide normal durations

  expected_output: >
    A comprehensive list of topics and their descriptions, along with a Gantt chart or 
    similar timeline visualization. The output must include:

    Topics: List of topics the user needs to learn.

    Description: Brief explanation of each topic.

    Duration: Estimated time required to complete each topic.

    Days: Number of days needed to cover the topic.

    Time Required: Total hours or weeks needed for mastery.

    Prerequisites: Topics or skills required before starting each topic.
   
  agent: analyze_bot


quality_task:
  description: >
    As a Quality Assurance Agent, your primary responsibility is to review the output generated by the quiz_bot,
    which includes the scores and topics to improve. You will carefully analyze the relevance, accuracy, and appropriateness 
    of these topics and durations to ensure they align with user expectations and quality standards. Your task involves 
    identifying any inconsistencies, errors, or areas for improvement in the analyze_bot output. Once the analysis is 
    complete, you will provide clear and constructive feedback to the bot, offering actionable suggestions to enhance its performance. 
    This feedback may include adjustments to topic selection to better match user needs, 
    recommendations for optimizing topic durations, and tips for improving overall relevance and accuracy.

  expected_output: >
    The expected output of your work is a detailed analysis report that highlights the strengths of the current 
    output, identifies any gaps or inconsistencies, and provides specific suggestions for improvement. Additionally, 
    you will present a refined version of the analyze_bot output, formatted as a markdown file without using '```'.

    The final output should include a generated roadmap in markdown format, 
    outlining the steps for implementing the improvements.  

    
  agent: quality_agent





